version: "3"

services:
  db:
    image: mongo:4.4.2-bionic
    container_name: mongo_db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: pm2_nodejs
    container_name: themoviedb_api
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOSTNAME=${MONGO_HOSTNAME}
      - MONGO_DB=${MONGO_DB}
      - API_KEY=${API_KEY}
      - PORT=${PORT}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
